/**
 * Mints the permanent invite the app ships with, and writes it into
 * src/lib/data/community.ts.
 *
 * The app cannot generate this itself. Creating an invite requires a bot
 * token, and a token shipped inside a desktop binary is a token published to
 * everyone who downloads it — so the link is generated once, here, and baked
 * in as a constant. "Automatic" means nobody types it; it does not mean the
 * client fetches it at runtime.
 *
 *   npm run discord:invite              # dry run
 *   npm run discord:invite -- --apply   # mint it and write the constant
 *
 * Idempotent: an existing never-expiring invite made by this bot is reused
 * rather than minting a second one, so re-running does not litter the server
 * with links or invalidate the one already shipped in a release.
 */

import { readFile, writeFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { PLAN } from './plan.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TARGET = join(ROOT, 'src', 'lib', 'data', 'community.ts');
const APPLY = process.argv.includes('--apply');

/** Where the invite drops people. The first channel of the first category. */
const LANDING = PLAN[0].channels[0];

async function loadDotEnv() {
	let raw;
	try {
		raw = await readFile(join(ROOT, '.env'), 'utf-8');
	} catch {
		return;
	}
	for (const line of raw.split(/\r?\n/)) {
		const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
		if (!m) continue;
		if (!(m[1] in process.env)) process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
	}
}

await loadDotEnv();
const GUILD = process.env.DISCORD_GUILD_ID;
if (!process.env.DISCORD_BOT_TOKEN || !GUILD) {
	console.error('Set DISCORD_BOT_TOKEN and DISCORD_GUILD_ID. See scripts/discord/README.md.');
	process.exit(1);
}

const A = 'https://discord.com/api/v10';
const H = {
	Authorization: 'Bot ' + process.env.DISCORD_BOT_TOKEN,
	'Content-Type': 'application/json',
	'User-Agent': 'ReachInvite (https://github.com/alexandrosnt/Reach, 0.5.1)'
};

async function api(method, path, body) {
	const res = await fetch(A + path, {
		method,
		headers: H,
		body: body ? JSON.stringify(body) : undefined
	});
	if (!res.ok) throw new Error(`${method} ${path} -> ${res.status}: ${await res.text()}`);
	return res.status === 204 ? null : res.json();
}

const slugOf = (n) => n.toLowerCase().replace(/^[^a-z0-9]+/u, '');

const guild = await api('GET', `/guilds/${GUILD}`);
const channels = await api('GET', `/guilds/${GUILD}/channels`);
const landing = channels.find((c) => c.type !== 4 && slugOf(c.name) === LANDING.name);
if (!landing) {
	console.error(`No #${LANDING.name} channel. Run: npm run discord:setup -- --apply`);
	process.exit(1);
}

const me = await api('GET', '/users/@me');
console.log(`Guild:   ${guild.name}`);
console.log(`Landing: #${landing.name}`);
console.log(`Mode:    ${APPLY ? 'APPLY' : 'dry run - nothing will change'}\n`);

// A permanent invite is max_age 0 (never expires) and max_uses 0 (unlimited).
// Anything else would expire in a shipped binary, which is the one place a
// dead link is hardest to fix.
const existing = await api('GET', `/channels/${landing.id}/invites`);
let invite = existing.find(
	(i) => i.max_age === 0 && i.max_uses === 0 && !i.temporary && i.inviter?.id === me.id
);

if (invite) {
	console.log(`Reusing the existing permanent invite (${invite.uses} uses so far).`);
} else if (APPLY) {
	invite = await api('POST', `/channels/${landing.id}/invites`, {
		max_age: 0,
		max_uses: 0,
		temporary: false,
		unique: false
	});
	console.log('Minted a new permanent invite.');
} else {
	console.log('Would mint a new permanent invite.');
}

if (!invite) {
	console.log('\nRe-run with --apply to make it real.');
	process.exit(0);
}

const url = `https://discord.gg/${invite.code}`;
console.log(`Invite:  ${url}`);

// Unlike a webhook URL, this one is meant to be public: it is shipped in the
// binary and shown to every user. It is safe to print and safe to commit.
const file = `/**
 * Where the Reach community lives.
 *
 * Generated by scripts/discord/invite.mjs — run \`npm run discord:invite\` to
 * refresh it. The invite never expires and has unlimited uses, because a link
 * baked into a shipped binary is the worst possible place for one that dies.
 *
 * This is deliberately a constant rather than something fetched at runtime.
 * Minting an invite needs a bot token, and a token inside a desktop binary is
 * a token handed to everyone who downloads it.
 */

export const COMMUNITY = {
	/** Permanent invite, unlimited uses. Public by design. */
	discordInvite: '${url}',
	/** Shown in the UI instead of the raw URL. */
	discordLabel: 'discord.gg/${invite.code}'
} as const;
`;

if (APPLY) {
	await writeFile(TARGET, file.replace(/\n/g, '\r\n'), 'utf-8');
	console.log(`Wrote ${TARGET.replace(ROOT, '.')}`);
} else {
	console.log('Would write src/lib/data/community.ts');
	console.log('\nRe-run with --apply to make it real.');
}
