/**
 * Where the Reach community lives.
 *
 * Generated by scripts/discord/invite.mjs — run `npm run discord:invite` to
 * refresh it. The invite never expires and has unlimited uses, because a link
 * baked into a shipped binary is the worst possible place for one that dies.
 *
 * This is deliberately a constant rather than something fetched at runtime.
 * Minting an invite needs a bot token, and a token inside a desktop binary is
 * a token handed to everyone who downloads it.
 */

export const COMMUNITY = {
	/** Permanent invite, unlimited uses. Public by design. */
	discordInvite: 'https://discord.gg/CSbEybvDVV',
	/** Shown in the UI instead of the raw URL. */
	discordLabel: 'discord.gg/CSbEybvDVV',
	/** GitHub Sponsors. Free software, funded by the people who use it. */
	sponsorUrl: 'https://github.com/sponsors/alexandrosnt',
	sponsorLabel: 'github.com/sponsors/alexandrosnt'
} as const;
